#ifndef ANSI_CODES_H_
#define ANSI_CODES_H_

/* ASCII escape codes */
#define C0_BEL ('\a')
#define C0_BS  ('\b')
#define C0_HT  ('\t')
#define C0_VT  ('\v')
#define C0_LF  ('\n')
#define C0_FF  ('\f')
#define C0_CR  ('\r')
#define C0_ESC ('\033')
#define C0_DEL ('\177')

/* ANSI escape codes */
#define Fe_SS2 ('N')
#define Fe_SS3 ('O')
#define Fe_DCS ('P')
#define Fe_CSI ('[')
#define Fe_ST  ('\\')
#define Fe_OSC (']')
#define Fe_SOS ('X')
#define Fe_PM  ('^')
#define Fe_APC ('_')

#define C1_SS2 (0x8e)
#define C1_SS3 (0x8f)
#define C1_DCS (0x90)
#define C1_CSI (0x9b)
#define C1_ST  (0x9c)
#define C1_OSC (0x9d)
#define C1_SOS (0x98)
#define C1_PM  (0x9e)
#define C1_APC (0x9f)

#define CSI_CUU ('A')
#define CSI_CUD ('B')
#define CSI_CUF ('C')
#define CSI_CUB ('D')
#define CSI_CNL ('E')
#define CSI_CPL ('F')
#define CSI_CHA ('G')
#define CSI_CUP ('H')
#define CSI_ED  ('J')
#define CSI_EL  ('K')
#define CSI_SU  ('S')
#define CSI_SD  ('T')
#define CSI_HVP ('f')
#define CSI_SGR ('m')
#define CSI_AUX ('i')
#define CSI_DSR ('n')

#define CSI_SCP ('s')
#define CSI_RCP ('u')

/* SGR parameters */
#define SGR_RESET                     (0)
#define SGR_BOLD                      (1)
#define SGR_FAINT                     (2)
#define SGR_ITALIC                    (3)
#define SGR_UNDERLINE                 (4)
#define SGR_SLOW_BLINK                (5)
#define SGR_FAST_BLINK                (6)
#define SGR_INVERT                    (7)
#define SGR_CONCEAL                   (8)
#define SGR_STRIKE                    (9)
/* fonts */
#define SGR_PRIMARY_FONT              (10)
#define SGR_ALT_FONT_FIRST            (11)
#define SGR_ALT_FONT_LAST             (19)
#define SGR_FRAKTUR                   (20)

#define SGR_DBL_UNDERLINE             (21)
#define SGR_NORMAL_INTENSITY          (22)
#define SGR_NOT_ITALIC_BLACKLETTER    (23)
#define SGR_NOT_UNDERLINE             (24)
#define SGR_NOT_BLINK                 (25)
#define SGR_PROPORTIONAL              (26)
#define SGR_NOT_INVERT                (27)
#define SGR_NOT_CONCEAL               (28)
#define SGR_NOT_STRIKE                (29)
/* FG colors */
#define SGR_FG_COLOR_FIRST            (30)
#define SGR_FG_COLOR_BLACK            (30)
#define SGR_FG_COLOR_RED              (31)
#define SGR_FG_COLOR_GREEN            (32)
#define SGR_FG_COLOR_YELLOW           (33)
#define SGR_FG_COLOR_BLUE             (34)
#define SGR_FG_COLOR_MAGENTA          (35)
#define SGR_FG_COLOR_CYAN             (36)
#define SGR_FG_COLOR_WHITE            (37)
#define SGR_FG_COLOR_LAST             (37)
#define SGR_FG_COLOR_SET_8BIT         (38)
#define SGR_FG_COLOR_DEFAULT          (39)
/* BG colors */
#define SGR_BG_COLOR_FIRST            (40)
#define SGR_BG_COLOR_BLACK            (40)
#define SGR_BG_COLOR_RED              (41)
#define SGR_BG_COLOR_GREEN            (42)
#define SGR_BG_COLOR_YELLOW           (43)
#define SGR_BG_COLOR_BLUE             (44)
#define SGR_BG_COLOR_MAGENTA          (45)
#define SGR_BG_COLOR_CYAN             (46)
#define SGR_BG_COLOR_WHITE            (47)
#define SGR_BG_COLOR_LAST             (47)
#define SGR_BG_COLOR_SET_8BIT         (48)
#define SGR_BG_COLOR_DEFAULT          (49)

#define SGR_NOT_PROPORTIONAL          (50)
#define SGR_FRAMED                    (51)
#define SGR_ENCIRCLED                 (52)
#define SGR_OVERLINE                  (53)
#define SGR_NOT_FRAMED_ENCIRCLED      (54)
#define SGR_NOT_OVERLINE              (55)
#define SGR_UNDERLINE_COLOR_8BIT      (58)
#define SGR_UNDERLINE_COLOR_DEFAULT   (59)
/* 60-65 for ideograms */
#define SGR_SUPERSCRIPT               (73)
#define SGR_SUBSCRIPT                 (74)
#define SGR_NOT_SUPERSCRIPT_SUBSCRIPT (75)
/* bright FG colors */
#define SGR_FG_COLOR_BRIGHT_FIRST     (90)
#define SGR_FG_COLOR_BRIGHT_BLACK     (90)
#define SGR_FG_COLOR_BRIGHT_RED       (91)
#define SGR_FG_COLOR_BRIGHT_GREEN     (92)
#define SGR_FG_COLOR_BRIGHT_YELLOW    (93)
#define SGR_FG_COLOR_BRIGHT_BLUE      (94)
#define SGR_FG_COLOR_BRIGHT_MAGENTA   (95)
#define SGR_FG_COLOR_BRIGHT_CYAN      (96)
#define SGR_FG_COLOR_BRIGHT_WHITE     (97)
#define SGR_FG_COLOR_BRIGHT_LAST      (97)
/* bright BG colors */
#define SGR_BG_COLOR_BRIGHT_FIRST     (100)
#define SGR_BG_COLOR_BRIGHT_BLACK     (100)
#define SGR_BG_COLOR_BRIGHT_RED       (101)
#define SGR_BG_COLOR_BRIGHT_GREEN     (102)
#define SGR_BG_COLOR_BRIGHT_YELLOW    (103)
#define SGR_BG_COLOR_BRIGHT_BLUE      (104)
#define SGR_BG_COLOR_BRIGHT_MAGENTA   (105)
#define SGR_BG_COLOR_BRIGHT_CYAN      (106)
#define SGR_BG_COLOR_BRIGHT_WHITE     (107)
#define SGR_BG_COLOR_BRIGHT_LAST      (107)

#endif // ANSI_CODES_H_
