E(0,               "No error information")
E(EPERM,           "Operation not permitter")
E(ENOENT,          "No such file or directory")
E(ESRCH,           "No such process")
E(EINTR,           "Interrupted system call")
E(EIO,             "I/O error")
E(ENXIO,           "No such device or address")
E(E2BIG,           "Argument list too long")
E(ENOEXEC,         "Exec format error")
E(EBADF,           "Bad file descriptor")
E(ECHILD,          "No child process")
E(EAGAIN,          "Resource temporarily unavailable")
E(ENOMEM,          "Out of memory")
E(EACCES,          "Permission denied")
E(EFAULT,          "Bad address")
E(ENOTBLK,         "Block device required")
E(EBUSY,           "Mount device busy")
E(EEXIST,          "File exists")
E(EXDEV,           "Cross-device link")
E(ENODEV,          "No such device")
E(ENOTDIR,         "Not a directory")
E(EISDIR,          "Is a directory")
E(EINVAL,          "Invalid argument")
E(ENFILE,          "Too many open files in system")
E(EMFILE,          "No file descriptors available")
E(ENOTTY,          "Not a tty")
E(ETXTBSY,         "Text file busy")
E(EFBIG,           "File too large")
E(ENOSPC,          "No space left on device")
E(ESPIPE,          "Invalid seek")
E(EROFS,           "Read-only file system")
E(EMLINK,          "Too many links")
E(EPIPE,           "Broken pipe")
E(EDOM,            "Domain error")
E(ERANGE,          "Result not representable")
E(ENOMSG,          "No message of desired type")
E(EIDRM,           "Identifier removed")
E(ECHRNG,          "Channel number out of range")
E(EL2NSYNC,        "Level 2 not synchronized")
E(EL3HLT,          "Level 3 halted")
E(EL3RST,          "Level 3 reset")
E(ELNRNG,          "Link number out of range")
E(EUNATCH,         "Protocol driver not attached")
E(ENOCSI,          "No CSI structure available")
E(EL2HLT,          "Level 2 halted")
E(EDEADLK,         "Resource deadlock would occur")
E(ENOLCK,          "No locks available")
E(EBADE,           "Invalid exchange")
E(EBADR,           "Invalid request descriptor")
E(EXFULL,          "Exchange full")
E(ENOANO,          "No anode")
E(EBADRQC,         "Invalid request code")
E(EBADSLT,         "Invalid slot")
E(EBFONT,          "Bad font file format")
E(ENOSTR,          "Device not a stream")
E(ENODATA,         "No data available")
E(ETIME,           "Device timeout")
E(ENOSR,           "Out of streams resources")
E(ENONET,          "Machine is not on the network")
E(ENOPKG,          "Package not installed")
E(EREMOTE,         "Object is remote")
E(ENOLINK,         "Link has been severed")
E(EADV,            "Advertise error")
E(ESRMNT,          "Srmount error")
E(ECOMM,           "Communication error on send")
E(EPROTO,          "Protocol error")
E(EMULTIHOP,       "Multihop attempted")
E(EBADMSG,         "Bad message")
E(ENOTUNIQ,        "Name not unique on network")
E(EBADFD,          "File descriptor in bad state")
E(EREMCHG,         "Remote address changed")
E(ELIBACC,         "Cannot access a needed shared library")
E(ELIBBAD,         "Accessing a corrupted shared library")
E(ELIBSCN,         ".lib section in a.out corrupted")
E(ELIBMAX,         "Attempting to link in too many shared libraries")
E(ELIBEXEC,        "Cannot exec a shared library directly")
E(ENOSYS,          "Function not implemented")
E(ENOTEMPTY,       "Directory not empty")
E(ENAMETOOLONG,    "Filename too long")
E(ELOOP,           "Symbolic link loop")
E(EOPNOTSUPP,      "Operation not supported")
E(EPFNOSUPPORT,    "Protocol family not supported")
E(ECONNRESET,      "Connection reset by peer")
E(ENOBUFS,         "No buffer space available")
E(EAFNOSUPPORT,    "Address family not supported by protocol")
E(EPROTOTYPE,      "Protocol wrong type for socket")
E(ENOTSOCK,        "Not a socket")
E(ENOPROTOOPT,     "Protocol not available")
E(ESHUTDOWN,       "Cannot send after socket shutdown")
E(ECONNREFUSED,    "Connection refused")
E(EADDRINUSE,      "Address in use")
E(ECONNABORTED,    "Connection aborted")
E(ENETUNREACH,     "Network unreachable")
E(ENETDOWN,        "Network is down")
E(ETIMEDOUT,       "Operation timed out")
E(EHOSTDOWN,       "Host is down")
E(EHOSTUNREACH,    "Host is unreachable")
E(EINPROGRESS,     "Operation in progress")
E(EALREADY,        "Operation already in progress")
E(EDESTADDRREQ,    "Destination address required")
E(EMSGSIZE,        "Message too large")
E(EPROTONOSUPPORT, "Protocol not supported")
E(ESOCKTNOSUPPORT, "Socket type not supported")
E(EADDRNOTAVAIL,   "Address not available")
E(ENETRESET,       "Connection reset by network")
E(EISCONN,         "Socket is connected")
E(ENOTCONN,        "Socket not connected")
E(ETOOMANYREFS,    "Too many references: cannot splice")
E(EUSERS,          "Too many users")
E(EDQUOT,          "Quota exceeded")
E(ESTALE,          "Stale file handle")
E(ENOTSUP,         "Not supported")
E(EILSEQ,          "Illegal byte sequence")
E(EOVERFLOW,       "Value too large for data type")
E(ECANCELED,       "Operation canceled")
E(ENOTRECOVERABLE, "State not recoverable")
E(EOWNERDEAD,      "Previous owner died")
E(ESTRPIPE,        "Streams pipe error")
